name: "Install docker"
description: "Install latest available version of docker"
author: "skupper@googlegroups.com"
runs:
  using: "composite"
  steps:
    - id: docker-install
      name: Installing docker
      shell: bash
      run: |
        sudo systemctl enable --now docker
        sudo systemctl enable --now docker.socket
        sudo usermod -a -G docker "$USER"
    - id: docker-version
      name: Docker version
      shell: bash
      run: |
        docker version
