name: "Install podman"
description: "Install latest available version of podman"
author: "skupper@googlegroups.com"
runs:
  using: "composite"
  steps:
    - id: podman-install
      name: Installing podman
      shell: bash
      run: |
        sudo apt-get -y install podman
        systemctl --user enable --now podman
        systemctl --user enable --now podman.socket
    - id: podman-version
      name: Podman version
      shell: bash
      run: |
        podman version
