name: Test the collection
on:
  pull_request:
    branches: [v2-dev]
  push:
    branches: [v2-dev]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./ansible_collections/skupper/v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: Install ansible, ansible-lint, yamllint
        run: pip3 install yamllint ansible ansible-lint virtualenv
      - name: Run ansible-lint
        run: cd ansible_collections/skupper/v2 && make lint
      - name: Run sanity tests
        run: cd ansible_collections/skupper/v2 && make sanity
      - name: Run unit tests
        run: cd ansible_collections/skupper/v2 && make unit
  e2e-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./ansible_collections/skupper/v2
      - name: Build skupper-router
        uses: ./ansible_collections/skupper/v2/.github/actions/build-router
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: Minikube
        uses: ./ansible_collections/skupper/v2/.github/actions/minikube
      - name: Docker
        uses: ./ansible_collections/skupper/v2/.github/actions/docker
      - name: Podman
        uses: ./ansible_collections/skupper/v2/.github/actions/podman
      - name: Run integration tests
        run: cd ansible_collections/skupper/v2 && make integration
